// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sblomrejdmexbcikxvqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNibG9tcmVqZG1leGJjaWt4dnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NzMzMzIsImV4cCI6MjA3MDI0OTMzMn0.wZ6q8OlWiht1QIFLrp9-FOKeepshVEJ9iPK9SXV3jHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});